Add english translation of chapter 4 : avoid autocomplete
cnumr/best-practices pull request #419
Opened 2023-01-18 10:40 UTC by rlemaire

2023-01-18 13:00 UTC, ACTLEM requested changes

2023-01-18 13:00 UTC, ACTLEM commented on chapters/BP_004_en.md
> +| The number of ...        | is equalt to or below |
```suggestion
| The number of ...        | is equal to or less than |  
```

2023-01-18 14:22 UTC, rlemaire commented on chapters/BP_004_en.md
> +- Add a delay of a few tenths of a second between the addition of a character and the request: this makes it possible not to trigger a request if the user has not finished typing.
I disagree with the use of « by » instead of with.

2023-06-14 14:17 UTC, ACTLEM approved these changes

2023-06-14 14:17 UTC, merged