Add english translation of chapter 15 : Choose the most appropriate t…
cnumr/best-practices pull request #430
Opened 2023-01-24 12:55 UTC by rlemaire

…echnologies

2023-03-05 21:58 UTC, EmmanuelDemey requested changes

2023-03-05 21:58 UTC, EmmanuelDemey commented on chapters/BP_015_en.md
> +### Exemple
Example

2023-03-09 08:13 UTC, EmmanuelDemey approved these changes

2023-04-30 17:22 UTC, tbroyer requested changes

2023-04-30 17:22 UTC, tbroyer commented on chapters/BP_015_en.md
> +### Exemple
That was changed in the wrong file.
```suggestion
### Example
```

2023-04-30 17:22 UTC, tbroyer commented on chapters/BP_015_fr.md
> +### Example
Rollback the second commit.
```suggestion
### Exemple
```

2023-06-24 11:18 UTC, EmmanuelDemey approved these changes

2023-06-25 18:58 UTC, merged