Corrections de fautes d'orthographes
cnumr/best-practices pull request #511
Opened 2023-10-23 20:22 UTC by gouz

Bonjour,

J'ai fait une passe sur toutes les bonnes pratiques en FR.

2023-10-24 07:21 UTC, rlemaire requested changes

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_032_fr.md
> +| d'URLs intégrant une quantité et / ou un nombre significatif de code CSS / Javascript (inline)   | 2  |
Pas de pluriels pour les acronymes (enfin le s est à la fin de locationS).

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_038_fr.md
> +Les sites d’actualités utilisent très souvent ce procédé, qui permet d’identifier clairement les zones qui nécessitent
« de l'actualité » (non dénombrable) est correct

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_040_fr.md
> +Certains frameworks, ici Bootstrap, permettent de créer des bibliothèques sur mesure qui ne contenient que les portions réellement
contenient ?

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_096_fr.md
> +Les pages d'erreurs (40x, 50x) doivent être les plus légères possibles, et même idéalement inexistantes. En effet, lorsque le navigateur demande une ressource qui n’existe pas (image, feuille de styl
Ca me parait plus correct au singulier ici.

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_096_fr.md
> +De plus, certains CMS exécutent leur routine de recherche de contenus (dans la base de données) pour tenter de trouver une ressource demandée. Par conséquent, du code serveur est exécuté, le serveur
Le singulier me parait correct (indénombrable)

2023-10-24 07:21 UTC, rlemaire commented on chapters/BP_4021_fr.md
> +n'y avoir que peu, voire pas du tout d'utilisateur connecté la nuit. Dans ce cas, il n'est pas nécessaire d'utiliser
Le pluriel me parait correct

2023-10-24 07:30 UTC, gouz commented on chapters/BP_032_fr.md
> +| d'URLs intégrant une quantité et / ou un nombre significatif de code CSS / Javascript (inline)   | 2  |
Corrigé

2023-10-24 07:32 UTC, gouz commented on chapters/BP_040_fr.md
> +Certains frameworks, ici Bootstrap, permettent de créer des bibliothèques sur mesure qui ne contenient que les portions réellement
corrigé, désolé

2023-10-26 16:12 UTC, rlemaire approved these changes

2023-10-26 16:12 UTC, merged